
os: Visual Studio 2015

environment:
  matrix:
    - ARCH:                x64
      D_COMPILER:          dmd
      D_VERSION:           2.071.2
      C_COMPILER:          MSVC

artifacts:
  - path: src/dmd.exe
    name: dmd
  - path: phobos64.lib
    name: phobos

init:
  - git config --global core.autocrlf input

build_script:
  - cd c:/projects/
  - call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - bash --version
  - appveyor DownloadFile "https://ftp.gnu.org/gnu/make/make-4.2.tar.gz" -FileName make.tar.gz
  - md make
  - cd make
  - 7z x ..\make.tar.gz -so | 7z x -si -ttar > nul
  - cd make-4.2
  - ps: cmd /C '"c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 && .\build_w32.bat > $null'
  - cp WinRel/gnumake.exe ../make.exe
  - cd ..
  - make --version
  - sh --login /c/projects/dmd/appveyor.sh

test_script: true
